version: '3.8'
services:
  db:
    image: postgres:15
    container_name: luxmed-terms-search-db
    environment:
      POSTGRES_DB: luxmed_terms_search
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: luxmed-terms-search-app
    depends_on:
      - db
      - chrome
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/luxmed_terms_search
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      ENCRYPTION_KEY: rYZFRt1/FA3KuaP3tcfjz8wO9nOnINcgB/QW1cIePwo=
      SELENIUM_REMOTE_URL: http://chrome:4444/wd/hub
    ports:
      - "8080:8080"

  chrome:
    image: selenium/standalone-chrome:latest
    hostname: chrome
    ports:
      - "4444:4444"
    privileged: true
    shm_size: 2g

volumes:
  db_data: