luxmed:
  email: ${LUXMED_EMAIL:}
  password: ${LUXMED_PASSWORD:}
notification:
  telegram:
    chat-id: ${TELEGRAM_CHAT_ID:}
    token: ${TELEGRAM_TOKEN:}

logging:
  level:
    pl.mbalcer.luxmedreservation: debug

spring:
  application.name: luxmed-search-terms
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true